version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474" # HTTP para el Browser
      - "7687:7687" # Protocolo Bolt para drivers
    environment:
      - NEO4J_AUTH=neo4j/password123 # Define tu contraseña aquí
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data: